### ISSUE TITLE
Pycirkuit crashes when trying to export to TIkZ

### ISSUE THREAD

**Issue by aniolm9** [orestesmas/pycirkuit#14] opened 2019-02-06 09:18 UTC
### System information
Debian 9.7
Python 3.5.3

### Expected behaviour
A dialog displaying the TIkZ code or asking where to save the TIkZ file should appear.

### Actual behaviour
Pycirkuit crashes with the following error:

```
Traceback (most recent call last):
  File "/opt/pycirkuit/venv/lib/python3.5/site-packages/pycirkuit/mainwindow.py", line 363, in on_exportButton_clicked
    dst = "{dstFile}".format(dstFile=lastWD+'/'+self.openedFilename.partition('.')[0]+".tikz")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
Aborted
```

### Reproduce the behaviour
Copy some macros to the text box, then click the button _Process and display_ and finally click the button _Export to TIkZ_.

**Comment by orestesmas** [comment] 2019-02-06 12:48
Cannot reproduce, even with an empty configuration file.

Please try to be more specific about the running conditions you have (checked out branch, configuration file contents prior to executing, etc.)

In GNU/Linux systems, the config file is stored at
```
~/.config/UPC/pycirkuit.conf

**Comment by orestesmas** [comment] 2019-02-06 13:57
Unable to reproduce. Closing. Feel free to reopen it if more details can be provided.

**Closed as completed by orestesmas** 2019-02-06 13:57 UTC
Labels: bug
